#!/bin/bash
#SBATCH --job-name=VeloF
#SBATCH --output=output_res/job-velo-%j.out
#SBATCH --error=log_res/job-velo-%j.log
#SBATCH --time=5:59:59
#SBATCH --mem-per-cpu=11G
#SBATCH --cpus-per-task=4
#SBATCH --array=1-4

source activate PGxG

INDEXFILE="./VeloTestF"

INDEX=$(awk "NR==$SLURM_ARRAY_TASK_ID" $INDEXFILE)
INDEX_ARR=(`echo ${INDEX}`)

DRUG=${INDEX_ARR[0]}
RN=${INDEX_ARR[1]}
SEED=${INDEX_ARR[2]}
EPOCH=${INDEX_ARR[3]}
BS=${INDEX_ARR[4]}
LDR=${INDEX_ARR[5]}
WD=${INDEX_ARR[6]}
WD1=${INDEX_ARR[7]}
WD2=${INDEX_ARR[8]}
HD=${INDEX_ARR[9]}
LR=${INDEX_ARR[10]}
LR1=${INDEX_ARR[11]}
LR2=${INDEX_ARR[12]}
LAM1=${INDEX_ARR[13]}
LAM2=${INDEX_ARR[14]}

LOG_ROOT="/groups/collinsgrp/projects/DomainGeneralization/VelodromeF/logs"
RES_ROOT="/home/hnoghabi/PGx/DataTL/Res/VelodromeF/results"
MOD_ROOT="/groups/collinsgrp/projects/DomainGeneralization/VelodromeF/models"

LOG_DIR="${LOG_ROOT}/${DRUG}/Save${RN}_${SEED}_${EPOCH}_${BS}_${LDR}_${WD}_${WD1}_${WD2}_${HD}_${LR}_${LR1}_${LR2}_${LAM1}_${LAM2}"
RES_DIR="${RES_ROOT}/${DRUG}/Save${RN}_${SEED}_${EPOCH}_${BS}_${LDR}_${WD}_${WD1}_${WD2}_${HD}_${LR}_${LR1}_${LR2}_${LAM1}_${LAM2}"
MOD_DIR="${MOD_ROOT}/${DRUG}/Save${RN}_${SEED}_${EPOCH}_${BS}_${LDR}_${WD}_${WD1}_${WD2}_${HD}_${LR}_${LR1}_${LR2}_${LAM1}_${LAM2}"

GPU=0

python ./TestVelodrome.py --drug ${DRUG} --save_logs ${LOG_DIR} --save_models ${LOG_DIR} --save_results ${RES_DIR} --save_models ${MOD_DIR} --epoch ${EPOCH} --hd ${HD} --bs ${BS} --ldr ${LDR} --lr ${LR} --lr1 ${LR1} --lr2 ${LR2} --wd ${WD} --wd1 ${WD1} --wd2 ${WD2} --seed ${SEED} --gpu ${GPU} --lam1 ${LAM1} --lam2 ${LAM2} --data_root "Data/"

